import { EnemyDef, EnemyKind } from './types';

export const ENEMIES: Record<EnemyKind, EnemyDef> = {
  drone: {
    kind: 'drone',
    name: 'Swarm Drone',
    hp: 35,
    speed: 1.6,
    armor: 0,
    bounty: 6,
    damage: 1,
    color: 'rose',
    glyph: 'd',
  },
  walker: {
    kind: 'walker',
    name: 'Armored Walker',
    hp: 140,
    speed: 0.85,
    armor: 6,
    bounty: 14,
    damage: 2,
    color: 'orange',
    glyph: 'W',
  },
  shielded: {
    kind: 'shielded',
    name: 'Shielded Trooper',
    hp: 70,
    speed: 1.1,
    armor: 2,
    shield: 60,
    bounty: 12,
    damage: 2,
    color: 'sky',
    glyph: 'S',
  },
  stealth: {
    kind: 'stealth',
    name: 'Stealth Infiltrator',
    hp: 55,
    speed: 1.4,
    armor: 0,
    bounty: 16,
    damage: 3,
    stealth: true,
    color: 'violet',
    glyph: 'X',
  },
  boss: {
    kind: 'boss',
    name: 'Siege Mech',
    hp: 1800,
    speed: 0.55,
    armor: 12,
    shield: 350,
    bounty: 200,
    damage: 25,
    color: 'red',
    glyph: 'Ω',
  },
};

export const ENEMY_LIST = Object.values(ENEMIES);
