// DH Club — Narrative RPG · Cinematic chapter takeover
//
// When a fresh chapter_transition message arrives in story chat (either
// posted by the GM or generated by the Writer's Room), we briefly
// overlay the full viewport with a black-card title reveal. This is one
// of the few "earned" hero moments in the app — chapter drops are the
// rhythmic structure of a campaign and deserve a beat.
//
// Designed to be inserted at the page root (via portal). It self-mounts
// from any new chapter_transition message id it hasn't seen, displays
// for ~2.6s, then unmounts. Clicking the overlay dismisses early.
//
// Honors prefers-reduced-motion via motionSafe.

import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { Film, Bookmark } from 'lucide-react';
import { FLAMINGO } from '@/lib/narrative/flamingoTheme';
import {
  HERO_OVERLAY, HERO_CONTENT, motionSafe, haptic, EASE_OUT_QUART, TIMING,
} from '@/lib/narrative/motion';
import type { Message } from '@/lib/narrative/types';

interface Props {
  /** Latest message in the campaign. We diff against the last
   *  message id we showed an overlay for to decide whether to fire. */
  latestMessage: Message | null;
  /** Use Flamingo styling on the takeover card. Generic falls back
   *  to a neutral dark palette. */
  flamingo?: boolean;
}

export function ChapterTransitionOverlay({ latestMessage, flamingo }: Props) {
  const [shownId, setShownId] = useState<string | null>(null);
  const [active, setActive] = useState<Message | null>(null);

  useEffect(() => {
    if (!latestMessage) return;
    if (latestMessage.message_type !== 'chapter_transition') return;
    if (shownId === latestMessage.id) return;
    // Only honor messages from the last 30 seconds — prevents the
    // overlay from firing for historical chapter transitions when the
    // page first loads with old data.
    const age = Date.now() - new Date(latestMessage.created_at).getTime();
    if (age > 30_000) {
      setShownId(latestMessage.id);
      return;
    }
    setShownId(latestMessage.id);
    setActive(latestMessage);
    haptic('success');
    const t = setTimeout(() => setActive(null), 2600);
    return () => clearTimeout(t);
  }, [latestMessage, shownId]);

  if (typeof document === 'undefined') return null;

  return createPortal(
    <AnimatePresence>
      {active && <Overlay message={active} flamingo={!!flamingo} onDismiss={() => setActive(null)} />}
    </AnimatePresence>,
    document.body,
  );
}

function Overlay({ message, flamingo, onDismiss }: { message: Message; flamingo: boolean; onDismiss: () => void }) {
  const meta = message.metadata as any;
  const recap: string | undefined = meta?.recap ?? meta?.summary;
  const chapterNumber: number | null = typeof meta?.chapter_number === 'number'
    ? meta.chapter_number
    : null;

  return (
    <motion.div
      {...motionSafe(HERO_OVERLAY)}
      initial="initial"
      animate="animate"
      exit="exit"
      onClick={onDismiss}
      className="fixed inset-0 z-[110] flex items-center justify-center px-6 cursor-pointer"
      style={{
        background: flamingo
          ? `
            radial-gradient(70% 50% at 30% 0%, hsl(${FLAMINGO.pink} / 0.35), transparent 65%),
            radial-gradient(60% 50% at 100% 100%, hsl(${FLAMINGO.cyan} / 0.25), transparent 70%),
            hsl(${FLAMINGO.midnight} / 0.96)
          `
          : 'hsl(0 0% 4% / 0.96)',
        backdropFilter: 'blur(20px) saturate(140%)',
      }}
    >
      {/* Top + bottom neon rules — appear after the card lands */}
      {flamingo && (
        <>
          <motion.div
            aria-hidden
            initial={{ scaleX: 0, opacity: 0 }}
            animate={{ scaleX: 1, opacity: 1, transition: { duration: TIMING.cine, ease: EASE_OUT_QUART, delay: 0.15 } }}
            exit={{ scaleX: 0, opacity: 0 }}
            className="absolute inset-x-0 top-[10%] h-px origin-left"
            style={{
              background: `linear-gradient(90deg, transparent, hsl(${FLAMINGO.pink}), hsl(${FLAMINGO.cyan}), transparent)`,
              boxShadow: `0 0 12px hsl(${FLAMINGO.pink} / 0.6)`,
            }}
          />
          <motion.div
            aria-hidden
            initial={{ scaleX: 0, opacity: 0 }}
            animate={{ scaleX: 1, opacity: 1, transition: { duration: TIMING.cine, ease: EASE_OUT_QUART, delay: 0.15 } }}
            exit={{ scaleX: 0, opacity: 0 }}
            className="absolute inset-x-0 bottom-[10%] h-px origin-right"
            style={{
              background: `linear-gradient(90deg, transparent, hsl(${FLAMINGO.cyan}), hsl(${FLAMINGO.pink}), transparent)`,
              boxShadow: `0 0 12px hsl(${FLAMINGO.cyan} / 0.6)`,
            }}
          />
        </>
      )}

      <motion.div
        {...motionSafe(HERO_CONTENT)}
        initial="initial"
        animate="animate"
        exit="exit"
        className="max-w-md w-full text-center relative"
      >
        <p
          className="inline-flex items-center gap-1.5 text-[10px] font-extrabold uppercase tracking-[0.32em]"
          style={{ color: flamingo ? `hsl(${FLAMINGO.cyan})` : 'hsl(0 0% 80%)' }}
        >
          <Film className="w-3 h-3" />
          {flamingo ? 'Previously on… The Flamingo Protocol' : 'Previously on…'}
        </p>
        {chapterNumber !== null && (
          <p
            className="text-[11px] font-extrabold uppercase tracking-[0.32em] mt-3"
            style={{ color: flamingo ? `hsl(${FLAMINGO.gold})` : 'hsl(0 0% 60%)' }}
          >
            Chapter {chapterNumber}
          </p>
        )}
        <h1
          className="font-display text-[36px] sm:text-[46px] font-extrabold tracking-tight mt-2 leading-[1.02]"
          style={flamingo ? {
            backgroundImage: `linear-gradient(95deg, hsl(${FLAMINGO.paper}), hsl(${FLAMINGO.pink}) 55%, hsl(${FLAMINGO.cyan}))`,
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            color: 'transparent',
          } : { color: 'hsl(0 0% 96%)' }}
        >
          {message.body}
        </h1>
        {recap && (
          <p
            className="text-[13px] italic leading-snug mt-4 max-w-[42ch] mx-auto"
            style={{ color: flamingo ? `hsl(${FLAMINGO.paper} / 0.78)` : 'hsl(0 0% 75%)' }}
          >
            {recap}
          </p>
        )}
        <div className="mt-6 flex items-center justify-center gap-2">
          <span
            aria-hidden
            className="w-1 h-1 rounded-full"
            style={{
              background: flamingo ? `hsl(${FLAMINGO.pink})` : 'hsl(0 0% 70%)',
              boxShadow: flamingo ? `0 0 6px hsl(${FLAMINGO.pink})` : undefined,
            }}
          />
          <Bookmark className="w-3.5 h-3.5" style={{ color: flamingo ? `hsl(${FLAMINGO.pink})` : 'hsl(0 0% 70%)' }} />
          <span
            aria-hidden
            className="w-1 h-1 rounded-full"
            style={{
              background: flamingo ? `hsl(${FLAMINGO.cyan})` : 'hsl(0 0% 70%)',
              boxShadow: flamingo ? `0 0 6px hsl(${FLAMINGO.cyan})` : undefined,
            }}
          />
        </div>
        <p
          className="mt-5 text-[10px] font-bold uppercase tracking-[0.22em] opacity-50"
          style={{ color: flamingo ? `hsl(${FLAMINGO.paper})` : 'hsl(0 0% 70%)' }}
        >
          Tap to dismiss
        </p>
      </motion.div>
    </motion.div>
  );
}
