/**
 * Curated universe for Portfolio Wars (~150 top US tickers).
 * Keeps the picker fast and avoids API misses from obscure symbols.
 */
export interface Ticker {
  symbol: string;
  name: string;
  sector?: string;
}

export const TICKERS: Ticker[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Tech' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Tech' },
  { symbol: 'GOOGL', name: 'Alphabet Class A', sector: 'Tech' },
  { symbol: 'GOOG', name: 'Alphabet Class C', sector: 'Tech' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Consumer' },
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Tech' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Tech' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Auto' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway B', sector: 'Finance' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Tech' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Finance' },
  { symbol: 'V', name: 'Visa', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Finance' },
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Health' },
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Health' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Tech' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Health' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Media' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Tech' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Health' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Tech' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Tech' },
  { symbol: 'MRK', name: 'Merck', sector: 'Health' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Tech' },
  { symbol: 'ACN', name: 'Accenture', sector: 'Tech' },
  { symbol: 'LIN', name: 'Linde', sector: 'Materials' },
  { symbol: 'MCD', name: "McDonald's", sector: 'Consumer' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Finance' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health' },
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Telecom' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Media' },
  { symbol: 'INTC', name: 'Intel', sector: 'Tech' },
  { symbol: 'IBM', name: 'IBM', sector: 'Tech' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Tech' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Tech' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Tech' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Health' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrial' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrial' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Finance' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrial' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrial' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Travel' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer' },
  { symbol: 'UBER', name: 'Uber', sector: 'Tech' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Finance' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Tech' },
  { symbol: 'SQ', name: 'Block', sector: 'Finance' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Finance' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Tech' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Tech' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Tech' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Tech' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Tech' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Tech' },
  { symbol: 'ZM', name: 'Zoom', sector: 'Tech' },
  { symbol: 'SPOT', name: 'Spotify', sector: 'Media' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Travel' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Media' },
  { symbol: 'ROKU', name: 'Roku', sector: 'Media' },
  { symbol: 'PINS', name: 'Pinterest', sector: 'Media' },
  { symbol: 'SNAP', name: 'Snap', sector: 'Media' },
  { symbol: 'F', name: 'Ford', sector: 'Auto' },
  { symbol: 'GM', name: 'General Motors', sector: 'Auto' },
  { symbol: 'RIVN', name: 'Rivian', sector: 'Auto' },
  { symbol: 'LCID', name: 'Lucid Motors', sector: 'Auto' },
  { symbol: 'NIO', name: 'NIO', sector: 'Auto' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Health' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Health' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Health' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Health' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Health' },
  { symbol: 'CI', name: 'Cigna', sector: 'Health' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer' },
  { symbol: 'LOW', name: "Lowe's", sector: 'Consumer' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Travel' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Travel' },
  { symbol: 'AAL', name: 'American Airlines', sector: 'Travel' },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Travel' },
  { symbol: 'CCL', name: 'Carnival', sector: 'Travel' },
  { symbol: 'MAR', name: 'Marriott', sector: 'Travel' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'T', name: 'AT&T', sector: 'Telecom' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Telecom' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Media' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrial' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrial' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Defense' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Defense' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Defense' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Defense' },
  { symbol: 'EBAY', name: 'eBay', sector: 'Consumer' },
  { symbol: 'ETSY', name: 'Etsy', sector: 'Consumer' },
  { symbol: 'CHWY', name: 'Chewy', sector: 'Consumer' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Tech' },
  { symbol: 'LYFT', name: 'Lyft', sector: 'Tech' },
  { symbol: 'HOOD', name: 'Robinhood', sector: 'Finance' },
  { symbol: 'SOFI', name: 'SoFi Technologies', sector: 'Finance' },
  { symbol: 'AFRM', name: 'Affirm', sector: 'Finance' },
  { symbol: 'U', name: 'Unity Software', sector: 'Tech' },
  { symbol: 'TWLO', name: 'Twilio', sector: 'Tech' },
  { symbol: 'OKTA', name: 'Okta', sector: 'Tech' },
  { symbol: 'TEAM', name: 'Atlassian', sector: 'Tech' },
  { symbol: 'MDB', name: 'MongoDB', sector: 'Tech' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Tech' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Tech' },
  { symbol: 'ASML', name: 'ASML Holding', sector: 'Tech' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Tech' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Tech' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Health' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Health' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Health' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Health' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Health' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Health' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Health' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Health' },
  { symbol: 'HUM', name: 'Humana', sector: 'Health' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Finance' },
  { symbol: 'MCO', name: "Moody's", sector: 'Finance' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Finance' },
  { symbol: 'CME', name: 'CME Group', sector: 'Finance' },
  { symbol: 'COF', name: 'Capital One', sector: 'Finance' },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Finance' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Finance' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance' },
  { symbol: 'AIG', name: 'AIG', sector: 'Finance' },
  { symbol: 'MET', name: 'MetLife', sector: 'Finance' },
];

export const TICKER_MAP: Record<string, Ticker> =
  TICKERS.reduce((acc, t) => ((acc[t.symbol] = t), acc), {} as Record<string, Ticker>);

export function searchTickers(query: string, limit = 20): Ticker[] {
  const q = query.trim().toUpperCase();
  if (!q) return TICKERS.slice(0, limit);
  const exact: Ticker[] = [];
  const sym: Ticker[] = [];
  const name: Ticker[] = [];
  for (const t of TICKERS) {
    if (t.symbol === q) exact.push(t);
    else if (t.symbol.startsWith(q)) sym.push(t);
    else if (t.name.toUpperCase().includes(q)) name.push(t);
  }
  return [...exact, ...sym, ...name].slice(0, limit);
}
